version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/aada-backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels: ["dependencies", "backend"]

  - package-ecosystem: "npm"
    directory: "/aada-frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels: ["dependencies", "frontend"]
